<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0-windows10.0.19041.0</TargetFramework>
    <RootNamespace>Langu.Translation</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Langu.Core\Langu.Core.csproj" />
    <None Include="Runtime\translator_worker.py" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>
</Project>
