<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0-windows10.0.19041.0</TargetFramework>
    <UseWPF>true</UseWPF>
    <RootNamespace>Langu.Overlay</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Langu.Core\Langu.Core.csproj" />
  </ItemGroup>
</Project>
